spring:
  application:
    name: msvc-management
  r2dbc:
    url: r2dbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres
    username: postgres.vpdpfxxoxtzrfdwkgvxa
    password: RosarioChumpitaz20
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1
  webflux:
    base-path: /

server:
  port: 8086

logging:
  level:
    edu.pe.vallegrande: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always